services:
  api:
    build: ./api
    ports:
      - "5001:5001"
      - "5678:5678"
    environment:
      - FLASK_DEBUG=1
      - DEBUG_MODE=1

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://localhost:5001
    depends_on:
      - api
